server:
  port: 3001

db:
  type: 'mysql'
  port: 3306
  database: 'dmet'
  username: 'root'
  password: 'root'

db_test:
  type: 'mysql'
  port: 3306
  database: 'dmet'
  username: 'root'
  password: 'rladlsxogkftndlTek!!'

jwt:
  expriesIn: 3600
  secret: '1234'
